name = "SpectraUtils"
uuid = "a0c45ec9-8886-4288-b58f-471f3de187f0"
version = "1.0.0-DEV"
authors = ["Jan Kuhfeld <jan@kuhfeld.net> and contributors"]

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"

[extensions]
SpectraUtilsChainRulesCoreExt = "ChainRulesCore"
SpectraUtilsMonteCarloMeasurementsExt = "MonteCarloMeasurements"

[compat]
ChainRulesCore = "1"
MonteCarloMeasurements = "1"
QuadGK = "2.11.2"
Random = "1.11.0"
SpecialFunctions = "2.5.1"
julia = "1.6.7"

[extras]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ChainRulesTestUtils = "cdddcdb0-9152-4a09-a978-84456f9df70a"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SafeTestsets", "Test", "SpecialFunctions", "ChainRulesCore", "ChainRulesTestUtils", "Random"]
