name = "SpectraUtils"
uuid = "a0c45ec9-8886-4288-b58f-471f3de187f0"
version = "1.0.0-DEV"
authors = ["Jan Kuhfeld <jan@kuhfeld.net> and contributors"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"

[extensions]
SpectraUtilsChainRulesCoreExt = "ChainRulesCore"
SpectraUtilsMonteCarloMeasurementsExt = "MonteCarloMeasurements"
SpectraUtilsNonlinearSolveExt = "NonlinearSolve"
SpectraUtilsTuringExt = "Turing"

[compat]
ChainRulesCore = "1"
ComponentArrays = "0.15.30"
Distributions = "0.25.122"
FiniteDiff = "2.29.0"
ForwardDiff = "1.3.0"
MonteCarloMeasurements = "1"
NonlinearSolve = "4.12.0"
QuadGK = "2.11.2"
Random = "1.11.0"
SpecialFunctions = "2.5.1"
Statistics = "1.11.1"
StatsAPI = "1.8.0"
Turing = "0.41.4"
julia = "1.6.7"

[extras]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ChainRulesTestUtils = "cdddcdb0-9152-4a09-a978-84456f9df70a"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"

[targets]
test = ["SafeTestsets", "Test", "SpecialFunctions", "ChainRulesCore", "ChainRulesTestUtils", "Random", "Turing", "NonlinearSolve"]
